# Generated by Django 5.2.7 on 2025-10-20 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userachievement',
            old_name='Achievement',
            new_name='achievement',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='xp_vaule',
            new_name='xp_value',
        ),
        migrations.AddField(
            model_name='userworkout',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
