# Generated by Django 5.2.7 on 2025-10-21 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_userworkout_user_remove_userworkout_workout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='userprofile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
